### ISSUE TITLE
React-Native 0.47 errors onChange

### ISSUE THREAD

**Issue by KaniRobinson** [harshq/react-native-mentions#8]
React-Native Errors on 
`
onChange={(event) => {
  this.setState({
    textInputHeight: this.props.textInputMinHeight >= event.nativeEvent.contentSize.height ? this.props.textInputMinHeight : event.nativeEvent.contentSize.height,
  });
} }
`
at event.nativeEvent.contentSize.height

**Comment by jensoleg** [comment]
Got the same error om RN 0.47
This might be because of a breaking change in RN 0.46

https://github.com/facebook/react-native/commit/bac84ce207a0466cec95626131063751eb48b964 

Change OnChange to onContentSizeChange in this lib's index.js  file and things will work again

Didn't notice already a PR. check it out

**Comment by harshq** [comment]
Hey! @KaniRobinson Was bit busy with the work lately. Will merge your PR tomorrow. Thanks for that.
